name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
      - name: Run Darker
        uses: akaihola/darker@1.7.0
        with:
          options: --check --diff --color --config pyproject.toml
          src: "."
          revision: origin/develop...
          lint: pylint
          version: "@baseline-clone-fix"
