name: Linter

# triggers for our workflow
on:
  # opening a pull request to master branch will be a trigger
  pull_request:
    branches:
      - master
  # any code pushed to master branch will also be a trigger
  push:
    branches:
      - master

jobs:
  lint:
    timeout-minutes: 8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run Darker
        uses: akaihola/darker@1.6.1
        with:
          options: --check -S --diff --color --config pyproject.toml
          src: "."
          lint: "pylint"
